APP_NAME: portal
API:
  LISTEN_ADDR: :3000
  DEBUG_MODE: false
SWAGGER:
  ENABLED: true
  PATH: ./swagger
TRANSLATION:
  FILE_PATH: ./i18n/definitions
  DEFAULT_LANGUAGE: en
DB:
  NAME: portal_local
  HOST: localhost
  PORT: 5432
  USER: postgres
  PASSWORD: ""
  SSL_MODE: disable
  POOL: 10
  MAX_IDLE_CONNECTIONS: 5
  CONNECTION_MAX_IDLE_TIME: 5m0s
  CONNECTION_MAX_LIFE_TIME: 30m0s
  CONNECTION_MAX_LIFE_TIME_JITTER: 5m0s
LOG:
  LEVEL: info
  OUTPUT: console
  FORMAT: json
TWILIO:
  ACCOUNT_SID: your_account_sid
  AUTH_TOKEN: your_auth_token
  VERIFY_SERVICE_SID: verify_service_sid
GMAIL:
  SMTP_SERVER: smtp.gmail.com
  SMTP_PORT: 587
  SMTP_USERNAME: username
  SMTP_PASSWORD: password
  FROM: user.name@gmail.com
THIRD_PARTY_SMS_PROVIDER: twilio
