APP_NAME: portal
API:
  LISTEN_ADDR: :3000
  DEBUG_MODE: false
AUTH:
  ENABLED: false
  CIPHER_KEY: 6c13b7338aa24366181369dbc6540f28
  AUTH_ISSUER: portal
  AUTH_ISSUER_UUID: portal-uuid
  AUTH_AUDIENCE: techx
  ACCESS_TOKEN_SECRET: af77aa93-42a0-4dae-add9-ade13453a770
  REFRESH_TOKEN_SECRET: 1b2a01e0-b6cc-4258-8965-d41b4bb2544d
  AUTH_SOFT_EXPIRY_DURATION: 168h0m0s
  AUTH_HARD_EXPIRY_DURATION: 720h0m0s
ADMIN_AUTH:
  CLIENT_ID: admin
  PASS_KEY: admin
GOOGLE_AUTH:
  DEBUG: true
  FORCE_APPROVAL: false
  CLIENT_STATE: google
  CLIENT_ID: google-client-id
  CLIENT_SECRET: google-client-secret
  REDIRECT_URL: https://secure.localhost.com/public/google/oauth/callback
SWAGGER:
  ENABLED: true
  PATH: ./swagger
TRANSLATION:
  FILE_PATH: ./i18n/definitions
  DEFAULT_LANGUAGE: en
DB:
  NAME: portal_local
  HOST: localhost
  PORT: 5432
  USER: postgres
  PASSWORD: ""
  SSL_MODE: disable
  POOL: 10
  MAX_IDLE_CONNECTIONS: 5
  CONNECTION_MAX_IDLE_TIME: 5m0s
  CONNECTION_MAX_LIFE_TIME: 30m0s
  CONNECTION_MAX_LIFE_TIME_JITTER: 5m0s
REDIS:
  HOST: localhost
  PORT: 6379
  POOL_SIZE: 30
  MIN_IDLE_CONNECTIONS: 10
  DIAL_TIMEOUT: 1s
  POOL_TIMEOUT: 1s
  READ_TIMEOUT: 1s
  WRITE_TIMEOUT: 1s
  IDLE_TIMEOUT: 30m0s
  IDLE_CHECK_FREQUENCY: 5m0s
  USERNAME: ""
  PASSWORD: ""
  HYSTRIX_TIMEOUT: 1000
  MAX_CONCURRENT_REQUESTS: 100
  SLEEP_WINDOW: 100
  ERROR_PERCENT_THRESHOLD: 10
  REQUEST_VOLUME_THRESHOLD: 100
LOG:
  LEVEL: info
  OUTPUT: console
  FORMAT: json
OTP:
  TTL: 10m0s
  MAX_RETRY_COUNT: 3
  MOCKING_ENABLED: false
  EMAIL_THIRD_PARTY_PROVIDER: gomail
  SMS_THIRD_PARTY_PROVIDER: msg91
RATE_LIMIT_ENABLED: true
RATE_LIMIT:
  DEFAULT_CONFIG:
    ENABLED: true
    ATTEMPTS: 10
    WINDOW_SECS: 3600
  ADMIN_USER_LIST:
    ENABLED: true
    ATTEMPTS: 100
    WINDOW_SECS: 600
  ADMIN_USER_UPDATE:
    ENABLED: true
    ATTEMPTS: 100
    WINDOW_SECS: 600
  ADMIN_COMPANY_LIST:
    ENABLED: true
    ATTEMPTS: 100
    WINDOW_SECS: 600
  ADMIN_COMPANY_UPDATE:
    ENABLED: true
    ATTEMPTS: 100
    WINDOW_SECS: 600
  ADMIN_REFERRAL_LIST:
    ENABLED: true
    ATTEMPTS: 100
    WINDOW_SECS: 600
  ADMIN_REFERRAL_UPDATE:
    ENABLED: true
    ATTEMPTS: 100
    WINDOW_SECS: 600
  ADMIN_REFERRAL_EXPIRE:
    ENABLED: true
    ATTEMPTS: 100
    WINDOW_SECS: 600
  ADMIN_FETCH_AUTH_TOKEN:
    ENABLED: false
    ATTEMPTS: 0
    WINDOW_SECS: 0
  GOOGLE_OAUTH_EXCHANGE:
    ENABLED: true
    ATTEMPTS: 5
    WINDOW_SECS: 600
  GENERATE_OTP:
    ENABLED: true
    ATTEMPTS: 5
    WINDOW_SECS: 600
  RESEND_OTP:
    ENABLED: true
    ATTEMPTS: 5
    WINDOW_SECS: 600
  VERIFY_OTP:
    ENABLED: true
    ATTEMPTS: 10
    WINDOW_SECS: 600
  USER_FETCH_PROFILE:
    ENABLED: true
    ATTEMPTS: 100
    WINDOW_SECS: 600
  USER_UPDATE_PROFILE:
    ENABLED: true
    ATTEMPTS: 100
    WINDOW_SECS: 600
  USER_REGISTER:
    ENABLED: true
    ATTEMPTS: 5
    WINDOW_SECS: 3600
  COMPANY_LIST:
    ENABLED: true
    ATTEMPTS: 100
    WINDOW_SECS: 600
  COMPANY_USER_LIST:
    ENABLED: true
    ATTEMPTS: 100
    WINDOW_SECS: 600
  REFERRAL_REQUEST:
    ENABLED: true
    ATTEMPTS: 10
    WINDOW_SECS: 600
  REFERRAL_LIST:
    ENABLED: true
    ATTEMPTS: 10
    WINDOW_SECS: 600
  REFERRAL_UPDATE:
    ENABLED: true
    ATTEMPTS: 10
    WINDOW_SECS: 600
  MENTOR_LIST:
    ENABLED: true
    ATTEMPTS: 100
    WINDOW_SECS: 600
  MENTOR_REGISTER:
    ENABLED: true
    ATTEMPTS: 5
    WINDOW_SECS: 3600
GOOGLE_CLIENT:
  HOST: www.googleapis.com
  HTTP_TIMEOUT: 1000
  RETRY_COUNT: 0
  USERNAME: ""
  PASSWORD: ""
  HYSTRIX_TIMEOUT: 1000
  MAX_CONCURRENT_REQUESTS: 100
  REQUEST_VOLUME_THRESHOLD: 100
  SLEEP_WINDOW: 100
  ERROR_PERCENT_THRESHOLD: 10
  retryoncodes: []
  transport: null
REFERRAL_MAIL:
  SMTP_SERVER: smtp.gmail.com
  SMTP_PORT: 587
  SMTP_USERNAME: username
  SMTP_PASSWORD: password
  DOMAIN: domain.com
  FROM_NAME: User Name
  FROM_EMAIL: referral@domain.com
OTP_MAIL:
  SMTP_SERVER: smtp.gmail.com
  SMTP_PORT: 587
  SMTP_USERNAME: username
  SMTP_PASSWORD: password
  DOMAIN: domain.com
  FROM_NAME: User Name
  FROM_EMAIL: support@domain.com
REFERRAL:
  REQUESTER_REFERRAL_LIMIT: 20
  PROVIDER_REFERRAL_LIMIT: 10
  REFERRAL_MAX_LOOKUP_DURATION: 168h0m0s
RESUME_DIRECTORY: ./user_resumes
COMPANY_LIST_LIMIT: 100
POPULAR_COMPANY_LIST_LIMIT: 5
