APP_NAME: portal
API:
  LISTEN_ADDR: :3000
  DEBUG_MODE: false
AUTH:
  DEBUG_MODE: false
  CIPHER_KEY: 6c13b7338aa24366181369dbc6540f28
  AUTH_ISSUER: portal
  AUTH_ISSUER_UUID: portal-uuid
  AUTH_AUDIENCE: techx
  ACCESS_TOKEN_SECRET: af77aa93-42a0-4dae-add9-ade13453a770
  REFRESH_TOKEN_SECRET: 1b2a01e0-b6cc-4258-8965-d41b4bb2544d
  AUTH_SOFT_EXPIRY_DURATION: 168h0m0s
  AUTH_HARD_EXPIRY_DURATION: 720h0m0s
ADMIN_AUTH:
  CLIENT_ID: admin
  PASS_KEY: admin
SWAGGER:
  ENABLED: true
  PATH: ./swagger
TRANSLATION:
  FILE_PATH: ./i18n/definitions
  DEFAULT_LANGUAGE: en
DB:
  NAME: portal_local
  HOST: localhost
  PORT: 5432
  USER: postgres
  PASSWORD: ""
  SSL_MODE: disable
  POOL: 10
  MAX_IDLE_CONNECTIONS: 5
  CONNECTION_MAX_IDLE_TIME: 5m0s
  CONNECTION_MAX_LIFE_TIME: 30m0s
  CONNECTION_MAX_LIFE_TIME_JITTER: 5m0s
LOG:
  LEVEL: info
  OUTPUT: console
  FORMAT: json
TWILIO:
  ACCOUNT_SID: your_account_sid
  AUTH_TOKEN: your_auth_token
  VERIFY_SERVICE_SID: verify_service_sid
GMAIL:
  SMTP_SERVER: smtp.gmail.com
  SMTP_PORT: 587
  SMTP_USERNAME: username
  SMTP_PASSWORD: password
  FROM: user.name@gmail.com
REFERRAL:
  REQUESTER_REFERRAL_LIMIT: 20
  PROVIDER_REFERRAL_LIMIT: 10
  REFERRAL_MAX_LOOKUP_DURATION: 168h0m0s
COMPANY_LIST_LIMIT: 100
POPULAR_COMPANY_LIST_LIMIT: 5
THIRD_PARTY_SMS_PROVIDER: mocked
