APP_NAME: portal
API:
  LISTEN_ADDR: :3000
  DEBUG_MODE: false
SWAGGER:
  ENABLED: true
  PATH: ./swagger
DB:
  NAME: portal_local
  HOST: localhost
  PORT: 5432
  USER: postgres
  PASSWORD: ""
  SSL_MODE: disable
  POOL: 10
  MAX_IDLE_CONNECTIONS: 5
  CONNECTION_MAX_IDLE_TIME: 5m0s
  CONNECTION_MAX_LIFE_TIME: 30m0s
  CONNECTION_MAX_LIFE_TIME_JITTER: 5m0s
LOG:
  LEVEL: info
  OUTPUT: console
  FORMAT: json
