definitions:
    BulkUserDetailsResponse:
        properties:
            users:
                items:
                    $ref: '#/definitions/UserProfile'
                type: array
                x-go-name: Users
        type: object
        x-go-package: github.com/techx/portal/handler/response
    ErrorDetails:
        properties:
            code:
                type: string
                x-go-name: Code
            message:
                type: string
                x-go-name: Message
            message_severity:
                type: string
                x-go-name: MessageSeverity
        type: object
        x-go-package: github.com/techx/portal/handler
    ErrorResponse:
        properties:
            errors:
                items:
                    $ref: '#/definitions/ErrorDetails'
                type: array
                x-go-name: Errors
        type: object
        x-go-package: github.com/techx/portal/handler
    OTPRequest:
        properties:
            channel:
                type: string
                x-go-name: Channel
            otp:
                type: string
                x-go-name: OTP
            value:
                type: string
                x-go-name: Value
        type: object
        x-go-package: github.com/techx/portal/handler/request
    OTPResponse:
        properties:
            action:
                type: string
                x-go-name: Action
            status:
                type: string
                x-go-name: Status
            user_id:
                type: string
                x-go-name: UserID
        type: object
        x-go-package: github.com/techx/portal/handler/response
    RegisterUserV1Request:
        properties:
            first_name:
                type: string
                x-go-name: FirstName
            last_name:
                type: string
                x-go-name: LastName
            linkedin:
                type: string
                x-go-name: LinkedIn
            personal_email:
                type: string
                x-go-name: PersonalEmail
            phone_number:
                type: string
                x-go-name: PhoneNumber
            work_email:
                type: string
                x-go-name: WorkEmail
            years_of_experience:
                format: float
                type: number
                x-go-name: YearsOfExperience
        type: object
        x-go-package: github.com/techx/portal/handler/request
    RegisterUserV1Response:
        properties:
            success:
                type: boolean
                x-go-name: Success
            user_id:
                type: string
                x-go-name: UserID
        type: object
        x-go-package: github.com/techx/portal/handler/response
    UserProfile:
        properties:
            created_at:
                format: date-time
                type: string
                x-go-name: CreatedAt
            first_name:
                type: string
                x-go-name: FirstName
            last_name:
                type: string
                x-go-name: LastName
            linkedin:
                type: string
                x-go-name: LinkedIn
            personal_email:
                type: string
                x-go-name: PersonalEmail
            phone_number:
                type: string
                x-go-name: PhoneNumber
            role:
                type: string
                x-go-name: Role
            user_id:
                type: string
                x-go-name: UserID
            work_email:
                type: string
                x-go-name: WorkEmail
            years_of_experience:
                format: float
                type: number
                x-go-name: YearsOfExperience
        type: object
        x-go-package: github.com/techx/portal/handler/response
paths:
    /admin/user/details:
        get:
            operationId: bulkGetUsers
            parameters:
                - in: query
                  name: user_id
                  type: string
                  x-go-name: UserID
                - in: query
                  name: phone_number
                  type: string
                  x-go-name: PhoneNumber
                - in: query
                  name: first_name
                  type: string
                  x-go-name: FirstName
                - in: query
                  name: last_name
                  type: string
                  x-go-name: LastName
                - in: query
                  name: company
                  type: string
                  x-go-name: Company
                - in: query
                  name: role
                  type: string
                  x-go-name: Role
            responses:
                "200":
                    description: BulkUserDetailsResponse
                    schema:
                        $ref: '#/definitions/BulkUserDetailsResponse'
                "400":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "401":
                    description: ""
                "422":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "503":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            tags:
                - admin
    /public/auth/otp/generate:
        post:
            operationId: generateOTP
            parameters:
                - in: body
                  name: OTPRequest
                  required: true
                  schema:
                    $ref: '#/definitions/OTPRequest'
            responses:
                "200":
                    description: OTPResponse
                    schema:
                        $ref: '#/definitions/OTPResponse'
                "400":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "401":
                    description: ""
                "422":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "503":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            tags:
                - public
    /public/auth/otp/verify:
        post:
            operationId: verifyOTP
            parameters:
                - in: body
                  name: OTPRequest
                  required: true
                  schema:
                    $ref: '#/definitions/OTPRequest'
            responses:
                "200":
                    description: OTPResponse
                    schema:
                        $ref: '#/definitions/OTPResponse'
                "400":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "401":
                    description: ""
                "422":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "503":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            tags:
                - public
    /public/user/profile:
        get:
            operationId: userProfile
            parameters:
                - in: query
                  name: user_id
                  type: string
                  x-go-name: UserID
                - in: query
                  name: phone_number
                  type: string
                  x-go-name: PhoneNumber
            responses:
                "200":
                    description: UserProfile
                    schema:
                        $ref: '#/definitions/UserProfile'
                "400":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "401":
                    description: ""
                "422":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "503":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            tags:
                - public
    /public/user/register/v1:
        post:
            operationId: registerUserV1
            parameters:
                - in: header
                  name: X-Request-Trace-Id
                  type: string
                  x-go-name: RequestTraceID
                - in: body
                  name: RegisterUserV1Request
                  required: true
                  schema:
                    $ref: '#/definitions/RegisterUserV1Request'
            responses:
                "200":
                    description: RegisterUserV1Response
                    schema:
                        $ref: '#/definitions/RegisterUserV1Response'
                "400":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "401":
                    description: ""
                "422":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "503":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            tags:
                - public
swagger: "2.0"
