definitions:
    ErrorDetails:
        properties:
            code:
                type: string
                x-go-name: Code
            message:
                type: string
                x-go-name: Message
            message_severity:
                type: string
                x-go-name: MessageSeverity
        type: object
        x-go-package: github.com/techx/portal/handler
    ErrorResponse:
        properties:
            errors:
                items:
                    $ref: '#/definitions/ErrorDetails'
                type: array
                x-go-name: Errors
        type: object
        x-go-package: github.com/techx/portal/handler
    RegisterUserV1Request:
        properties:
            first_name:
                type: string
                x-go-name: FirstName
            last_name:
                type: string
                x-go-name: LastName
            linkedin:
                type: string
                x-go-name: LinkedIn
            personal_email:
                type: string
                x-go-name: PersonalEmail
            phone_number:
                type: string
                x-go-name: PhoneNumber
            work_email:
                type: string
                x-go-name: WorkEmail
            years_of_experience:
                format: double
                type: number
                x-go-name: YearsOfExperience
        type: object
        x-go-package: github.com/techx/portal/handler/request
    RegisterUserV1Response:
        properties:
            error:
                type: string
                x-go-name: Error
            success:
                type: boolean
                x-go-name: Success
        type: object
        x-go-package: github.com/techx/portal/handler/response
paths:
    /portal/v1/register:
        post:
            operationId: registerUserV1
            parameters:
                - in: header
                  name: X-Request-Trace-Id
                  type: string
                  x-go-name: RequestTraceID
                - in: header
                  name: X-User-Type
                  type: string
                  x-go-name: UserType
                - in: body
                  name: RegisterUserV1Request
                  schema:
                    $ref: '#/definitions/RegisterUserV1Request'
            responses:
                "200":
                    description: RegisterUserV1Response
                    schema:
                        $ref: '#/definitions/RegisterUserV1Response'
                "400":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "401":
                    description: ""
                "422":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "503":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            tags:
                - public
swagger: "2.0"
