definitions:
    BulkUserDetailsResponse:
        properties:
            users:
                items:
                    $ref: '#/definitions/UserProfile'
                type: array
                x-go-name: Users
        type: object
        x-go-package: github.com/techx/portal/handler/response
    Company:
        properties:
            id:
                format: int64
                type: integer
                x-go-name: ID
            name:
                type: string
                x-go-name: Name
        type: object
        x-go-package: github.com/techx/portal/handler/response
    CompanyListResponse:
        properties:
            companies:
                items:
                    $ref: '#/definitions/Company'
                type: array
                x-go-name: Companies
        type: object
        x-go-package: github.com/techx/portal/handler/response
    CompanyUser:
        properties:
            company:
                type: string
                x-go-name: Company
            name:
                type: string
                x-go-name: Name
            user_id:
                type: string
                x-go-name: UserID
        type: object
        x-go-package: github.com/techx/portal/handler/response
    CompanyUsersListResponse:
        properties:
            users:
                items:
                    $ref: '#/definitions/CompanyUser'
                type: array
                x-go-name: Users
        type: object
        x-go-package: github.com/techx/portal/handler/response
    ErrorResponse:
        properties:
            code:
                type: string
                x-go-name: Code
            message:
                type: string
                x-go-name: Message
            severity:
                type: string
                x-go-name: Severity
            title:
                type: string
                x-go-name: Title
        type: object
        x-go-package: github.com/techx/portal/handler/response
    GenerateOTPResponse:
        properties:
            action:
                type: string
                x-go-name: Action
        type: object
        x-go-package: github.com/techx/portal/handler/response
    OTPRequest:
        properties:
            channel:
                type: string
                x-go-name: Channel
            otp:
                type: string
                x-go-name: OTP
            value:
                type: string
                x-go-name: Value
        type: object
        x-go-package: github.com/techx/portal/handler/request
    ReferralRequest:
        properties:
            company:
                type: string
                x-go-name: Company
            job_link:
                type: string
                x-go-name: JobLink
            message:
                type: string
                x-go-name: Message
            provider_user_id:
                type: string
                x-go-name: ProviderUserID
            requester_user_id:
                type: string
                x-go-name: RequesterUserID
        type: object
        x-go-package: github.com/techx/portal/handler/request
    ReferralResponse:
        properties:
            success:
                type: boolean
                x-go-name: Success
        type: object
        x-go-package: github.com/techx/portal/handler/response
    RegisterUserV1Request:
        properties:
            company:
                type: string
                x-go-name: Company
            linkedin:
                type: string
                x-go-name: LinkedIn
            name:
                type: string
                x-go-name: Name
            personal_email:
                type: string
                x-go-name: PersonalEmail
            phone_number:
                type: string
                x-go-name: PhoneNumber
            role:
                type: string
                x-go-name: Role
            work_email:
                type: string
                x-go-name: WorkEmail
            years_of_experience:
                format: float
                type: number
                x-go-name: YearsOfExperience
        type: object
        x-go-package: github.com/techx/portal/handler/request
    RegisterUserV1Response:
        properties:
            action:
                type: string
                x-go-name: Action
            profile:
                $ref: '#/definitions/UserProfile'
        type: object
        x-go-package: github.com/techx/portal/handler/response
    UserProfile:
        properties:
            company:
                type: string
                x-go-name: Company
            created_at:
                format: date-time
                type: string
                x-go-name: CreatedAt
            linkedin:
                type: string
                x-go-name: LinkedIn
            name:
                type: string
                x-go-name: Name
            personal_email:
                type: string
                x-go-name: PersonalEmail
            phone_number:
                type: string
                x-go-name: PhoneNumber
            role:
                type: string
                x-go-name: Role
            status:
                type: string
                x-go-name: Status
            user_id:
                type: string
                x-go-name: UserID
            work_email:
                type: string
                x-go-name: WorkEmail
            years_of_experience:
                format: float
                type: number
                x-go-name: YearsOfExperience
        type: object
        x-go-package: github.com/techx/portal/handler/composers
    VerifyOTPResponse:
        properties:
            action:
                type: string
                x-go-name: Action
            profile:
                $ref: '#/definitions/UserProfile'
        type: object
        x-go-package: github.com/techx/portal/handler/response
paths:
    /admin/user/details:
        get:
            operationId: bulkGetUsers
            parameters:
                - in: query
                  name: status
                  type: string
                  x-go-name: Status
                - in: query
                  name: user_id
                  type: string
                  x-go-name: UserID
                - in: query
                  name: phone_number
                  type: string
                  x-go-name: PhoneNumber
                - in: query
                  name: name
                  type: string
                  x-go-name: Name
                - in: query
                  name: company
                  type: string
                  x-go-name: Company
                - in: query
                  name: role
                  type: string
                  x-go-name: Role
            responses:
                "200":
                    description: BulkUserDetailsResponse
                    schema:
                        $ref: '#/definitions/BulkUserDetailsResponse'
                "400":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "401":
                    description: ""
                "422":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "503":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            tags:
                - admin
    /public/auth/otp/generate:
        post:
            operationId: generateOTP
            parameters:
                - in: body
                  name: OTPRequest
                  required: true
                  schema:
                    $ref: '#/definitions/OTPRequest'
            responses:
                "200":
                    description: GenerateOTPResponse
                    schema:
                        $ref: '#/definitions/GenerateOTPResponse'
                "400":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "401":
                    description: ""
                "422":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "503":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            tags:
                - public
    /public/auth/otp/verify:
        post:
            operationId: verifyOTP
            parameters:
                - in: body
                  name: OTPRequest
                  required: true
                  schema:
                    $ref: '#/definitions/OTPRequest'
            responses:
                "200":
                    description: VerifyOTPResponse
                    schema:
                        $ref: '#/definitions/VerifyOTPResponse'
                "400":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "401":
                    description: ""
                "422":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "503":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            tags:
                - public
    /public/company/list:
        get:
            operationId: companyList
            responses:
                "200":
                    description: CompanyListResponse
                    schema:
                        $ref: '#/definitions/CompanyListResponse'
                "400":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "401":
                    description: ""
                "422":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "503":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            tags:
                - public
    /public/company/users/list:
        get:
            operationId: companyUsersList
            parameters:
                - in: header
                  name: X-User-Id
                  required: true
                  type: string
                  x-go-name: UserID
            responses:
                "200":
                    description: CompanyUsersListResponse
                    schema:
                        $ref: '#/definitions/CompanyUsersListResponse'
                "400":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "401":
                    description: ""
                "422":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "503":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            tags:
                - public
    /public/user/profile:
        get:
            operationId: userProfile
            parameters:
                - in: header
                  name: X-User-Id
                  required: true
                  type: string
                  x-go-name: UserID
            responses:
                "200":
                    description: UserProfile
                    schema:
                        $ref: '#/definitions/UserProfile'
                "400":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "401":
                    description: ""
                "422":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "503":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            tags:
                - public
    /public/user/referral/request:
        post:
            operationId: referralRequest
            parameters:
                - in: header
                  name: X-User-Id
                  required: true
                  type: string
                  x-go-name: UserID
                - in: body
                  name: Body
                  required: true
                  schema:
                    $ref: '#/definitions/ReferralRequest'
            responses:
                "200":
                    description: ReferralResponse
                    schema:
                        $ref: '#/definitions/ReferralResponse'
                "400":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "401":
                    description: ""
                "422":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "503":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            tags:
                - public
    /public/user/register/v1:
        post:
            operationId: registerUserV1
            parameters:
                - in: body
                  name: RegisterUserV1Request
                  required: true
                  schema:
                    $ref: '#/definitions/RegisterUserV1Request'
            responses:
                "200":
                    description: RegisterUserV1Response
                    schema:
                        $ref: '#/definitions/RegisterUserV1Response'
                "400":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "401":
                    description: ""
                "422":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "503":
                    description: ErrorResponse
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            tags:
                - public
swagger: "2.0"
