name: Static Checks

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'

      - name: Run Tests
        run: LOG_LEVEL=error make ci-test

  lint:
    runs-on: ubuntu-latest
    name: Run Lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'

      - name: Run Lint
        run: make ci-lint
